export declare function normalizarNatureza(s: string | null | undefined): string;
export declare function padSubelemento(sub: string | null | undefined): string;
export type QrConfigFields = {
    campos: string;
    separador: string;
};
export type EmpenhoQrData = {
    id?: number | string;
    numero_ficha?: string;
    projeto_atividade?: string;
    dotacao?: string;
    stn?: string;
    subelemento_codigo?: string;
    subelemento_descricao?: string;
    credor_id?: number | string;
    credor_numero?: string;
    credor_nome?: string;
    tipo_empenho?: number | string;
    historico?: string;
    valor_empenho?: number | string;
    emenda?: number | string;
    exercicio?: number | string;
    numero_contrato?: string;
    numero_convenio?: string;
    data_empenho?: string;
    usuario_id?: string;
    usuario_nome?: string;
    created_at?: string;
    updated_at?: string;
    data_liquidacao?: string;
    data_pagamento?: string;
    conta_liquidacao?: string;
    numero_op_liquidacao?: string;
    forma_pagamento_liquidacao?: string;
};
export declare function buildQrText(empenho: EmpenhoQrData, configQr: QrConfigFields): string;
export declare function gerarCodigoInterno(id: number): string;
export declare function parseCurrencyBR(value: string | null | undefined): number;
export declare function formatCurrencyBR(value: number | null | undefined): string;
